---
#Create VPC
- name: Create VPC
  ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr_block }}"
    region: "{{ aws_region }}"
  register: vpc_details

# Create public subnet AZ-1
- name: Creating public subnet on first AZ
  ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc_details.vpc.id }}"
    az: "{{ aws_az_1 }}"
    cidr: "{{ pub_sub_az_1_cidr }}"
    resource_tags:
      Name: "{{ pub_sub_az_1_name }}"
  register: pub_sub_az_1_details

# Create public subnet AZ-2
- name: Creating public subnet on second AZ
  ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc_details.vpc.id }}"
    az: "{{ aws_az_2 }}"
    cidr: "{{ pub_sub_az_2_cidr }}"
    resource_tags:
      Name: "{{ pub_sub_az_2_name }}"
  register: pub_sub_az_2_details

# Create private subnet AZ-1
- name: Creating private subnet on first AZ
  ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc_details.vpc.id }}"
    az: "{{ aws_az_1 }}"
    cidr: "{{ priv_sub_az_1_cidr }}"
    resource_tags:
      Name: "{{ priv_sub_az_1_name }}"
  register: priv_sub_az_1_details

# Create private subnet AZ-2
- name: Creating private subnet on second AZ
  ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc_details.vpc.id }}"
    az: "{{ aws_az_2 }}"
    cidr: "{{ priv_sub_az_2_cidr }}"
    resource_tags:
      Name: "{{ priv_sub_az_2_name }}"
  register: priv_sub_az_2_details

# Creating initial security group
- name: Creating initial server security group
  ec2_group:
    name: "{{ aws_initial_sg_name }}"
    description: "{{ aws_initial_sg_description }}"
    vpc_id: "{{ vpc_details.vpc.id }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "{{ ssh_range }}"

# Creating production server security group
- name: Creating production server security group
  ec2_group:
    name: "{{ aws_prod_sg_name }}"
    description: "{{ aws_prod_sg_description }}"
    vpc_id: "{{ vpc_details.vpc.id }}"
    rules:
      - proto: tcp
        from_port: "{{ aws_prod_sg_ssh_port }}"
        to_port: "{{ aws_prod_sg_ssh_port }}"
        cidr_ip: "{{ ssh_range }}"
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: "{{ inet_range }}"
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: "{{ inet_range }}"

# Creating internet gateway
- name: Creating internet gateway
  ec2_vpc_igw:
    vpc_id: "{{ vpc_details.vpc.id }}"
    state: present
  register: igw_details

# Create route table for public subnet
- name: Setting up public subnet route
  ec2_vpc_route_table:
    vpc_id: "{{ vpc_details.vpc.id }}"
    region: "{{ aws_region }}"
    tags:
      Name: PublicSubnets
    subnets: 
      - "{{ pub_sub_az_1_details.subnet.id }}"
      - "{{ pub_sub_az_2_details.subnet.id }}"
    routes:
      - dest: "{{ inet_range }}"
        gateway_id: "{{ igw_details.gateway_id }}"

# Create route table for private subnet
- name: Setting up private subnet route
  ec2_vpc_route_table:
    vpc_id: "{{ vpc_details.vpc.id }}"
    region: "{{ aws_region }}"
    tags:
      Name: PrivateSubnets
    subnets: 
      - "{{ priv_sub_az_1_details.subnet.id }}"
      - "{{ priv_sub_az_2_details.subnet.id }}"
    routes:
      - dest: "{{ vpc_cidr_block }}"
        gateway_id: local

# Create network access control list
- name: "Create a NACL to restrict traffic to desired ports"
  ec2_vpc_nacl:
    vpc_id: "{{ vpc_details.vpc.id }}"
    name: vpc_nacl
    region: "{{ aws_region }}" 
    subnets: [
        "{{ pub_sub_az_1_details.subnet.id }}", 
        "{{ pub_sub_az_2_details.subnet.id }}",
        "{{ priv_sub_az_1_details.subnet.id }}", 
        "{{ priv_sub_az_2_details.subnet.id }}"
    ]
    ingress: [
        [100, 'tcp', 'allow', "{{ ssh_range }}", null, null, 22, 22],
        [200, 'tcp', 'allow', "{{ ssh_range }}", null, null, "{{ aws_prod_sg_ssh_port }}", "{{ aws_prod_sg_ssh_port }}"],
        [300, 'tcp', 'allow', "{{ inet_range }}", null, null, 80, 80],
        [400, 'tcp', 'allow', "{{ inet_range }}", null, null, 443, 443]
        [500, 'tcp', 'allow', "{{ inet_range }}", null, null, 1024, 65535]
    ]
    egress: [
        [100, 'all', 'allow', "{{ inet_range }}", null, null, null, null]
    ]
    state: 'present'

