# Don't run over SSH
ansible_connection: local

#Creator Tag
creator: AnsibleUser

# VPC Details
vpc:
  name: AnsibleVPC
  region: us-west-1
  az_1: us-west-1a
  az_2: us-west-1c
  cidr: 10.0.0.0/16

#### Subnet details

# Public subnets
pub_sub_az_1:
  name: Public1a
  cidr: 10.0.0.0/24

pub_sub_az_2: 
  name: Public1c
  cidr: 10.0.1.0/24

# Private subnets
priv_sub_az_1:
  name: Private1a
  cidr: 10.0.128.0/24

priv_sub_az_2:
  name: Private1c
  cidr: 10.0.129.0/24

# IP ranges
range:
  inet: 0.0.0.0/0
  ssh: 0.0.0.0/0

# Security group information
sg:
  initial_name: PublicServersNonProd
  initial_description: allow SSH 
  prod_name: PublicServersProd
  prod_description: allow HTTP, HTTPS, non-default SSH
  prod_ssh_port: 2666

#IGW
igw_name: InternetGateway
